
---
- name: Join host to the mind.com domain
  hosts: windows
  become: false
  gather_facts: false
  tasks:
    - name: Join Domain 
      ansible.windows.win_domain_membership:
        dns_domain_name: mind.com
        hostname: mydomainclient
        domain_admin_user: administrator@mind.com
        domain_admin_password: asd123ASD@
        domain_ou_path: "OU=Windows,OU=Servers,DC=mind,DC=com"
        state: domain
      register: domain_state

    - name: Reboot host after domain join
      ansible.windows.win_reboot:
      when: domain_state.reboot_required
