- name: Ensure multiple local groups are present on Windows servers
  hosts: windows
  become: false
  gather_facts: false

  vars_prompt:
    - name: username
      prompt: What is your username?
      private: false

    - name: password
      prompt: What is your password?

  tasks:
    - win_domain_membership:
        dns_domain_name: mind.com
        hostname: server4
        domain_admin_user: 'Logging in as {{ username }}'
        domain_admin_password: 'Logging in as {{ password }}'
        domain_ou_path: "OU=Windows,OU=Servers,DC=mind,DC=com"
        state: domain
        reboot: true
      register: domain_state
